### ISSUE TITLE
Error: Package CL-OPENGL-LIBRARY does not exist.

### ISSUE THREAD

**Issue by jolby** [borodust/alien-works#2]
Linux x64 / SBCL 2.1.6
This project looks very cool and I realize it's pretty new. Feel free to close/ignore if you're not ready to deal with user submitted issues right now. I Just tried taking this package for a spin, pulled alien-works into my quicklisp local-projects dir. 

Line 1058 in src/host/host.lisp contains this line:

(cl-opengl-library:load-opengl-library)

When I commented it out I was able to load the system. It seems like the opengl library is actually loaded so I can proceed with trying it out.

**Comment by borodust** [comment]
Thank you for the report.

`alien-works` uses `cl-opengl` with the following patch https://github.com/3b/cl-opengl/pull/103

`alien-works` ain't ready yet - feel free to give it a go, but it's unlikely to work out of the box for now.  Potentially, I can break API anytime - it's still in active phase of research and development.

E.g. it's probably out of sync with `alien-works-foundation` system: I have bumped `Filament` version, but not yet updated the complied foreign library blob in aforementioned system.
