### ISSUE TITLE
iOS example?

### ISSUE THREAD

**Issue by aymanosman** [borodust/alien-works#3]
I see the project states that it supports iOS. Is this a planned feature or does it already work?
If so, is there an example of running on iOS?

**Comment by borodust** [comment]
Underlying technology behind `alien-works` fully supports macOS/iOS, but I don't have access to Apple hardware, so I never had a chance to try `alien-works` on those platforms.

**Comment by aymanosman** [comment]
Thanks for the info. I was under the impression that it was not easy to get any of the major Lisp implementations running on iOS.
